<a href="https://colab.research.google.com/github/heemene/COGS109GROUPA/blob/main/COGS109_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Below is the setup to import the datasets into Google Colab

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
import pandas as pd

#library dataset import and check
file_path = '/content/drive/MyDrive/library.csv'
df = pd.read_csv(file_path)
df.head()  # show the first few rows

,Sup Dist,Cost Code,Library Name,City,Zip Code,Square Footage,Year Built,Mon,Tue,Wed,Thur,Fri,Sat,Sun,Collection Size,Address and Location,ObjectId
0,1,604,Anthony Quinn,Los Angeles,90063,7275,1973,11-8,11/8/2022 12:00:00 AM,11/6/2022 12:00:00 AM,11-6,11-5,11-5,Closed,48134,3965 Cesar E. Chavez Ave.\nLos Angeles\n(34.04...,1
1,1,803,Baldwin Park,Baldwin Park,91706,15555,1969,Closed,12/8/2022 12:00:00 AM,1/8/2022 12:00:00 AM,1-8,10-5,10-5,Closed,64948,4181 Baldwin Park Blvd.\nBaldwin Park\n(34.088...,2
2,1,630,Bell,Bell,90201,4863,1960,Closed,10/8/2022 12:00:00 AM,10/6/2022 12:00:00 AM,11-5,11-5,12-5,Closed,36396,"4411 E. Gage Ave.\nBell\n(33.9783, -118.189)",3
3,1,631,Bell Gardens,Bell Gardens,90201,5119,1968,Closed,10/7/2022 12:00:00 AM,10/7/2022 12:00:00 AM,10-7,10-6,10-5,Closed,34771,"7110 S. Garfield Ave.\nBell Gardens\n(33.9672,...",4
4,1,616,Chet Holifield,Montebello,90640,5500,1969,12-7,12/7/2022 12:00:00 AM,11/6/2022 12:00:00 AM,11-6,Closed,Closed,Closed,31346,"1060 S. Greenwood Ave.\nMontebello\n(33.9935, ...",5

In [9]:

#median income dataset import and check
file_path = '/content/drive/MyDrive/medianinc.csv'
df = pd.read_csv(file_path)
df.head()  # show the first few rows

,placeDcid,placeName,Date:Median_Income_Household,Value:Median_Income_Household,Source:Median_Income_Household
0,zip/90003,90003,2011,28334,https://www.census.gov/programs-surveys/acs/da...
1,zip/90003,90003,2012,29174,https://www.census.gov/programs-surveys/acs/da...
2,zip/90003,90003,2013,29686,https://www.census.gov/programs-surveys/acs/da...
3,zip/90003,90003,2014,30016,https://www.census.gov/programs-surveys/acs/da...
4,zip/90003,90003,2015,30805,https://www.census.gov/programs-surveys/acs/da...

In [10]:
#lacrime dataset import and check
file_path = '/content/drive/MyDrive/lacrime.csv'
df = pd.read_csv(file_path)
df.head()  # show the first few rows

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,2010 Feb 20 12:00:00 AM,2010 Feb 20 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,2010 Sep 13 12:00:00 AM,2010 Sep 12 12:00:00 AM,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962
2,70309629,2010 Aug 09 12:00:00 AM,2010 Aug 09 12:00:00 AM,1515,13,Newton,1324,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,NaN,NaN,NaN,1300 E 21ST ST,NaN,34.0224,-118.2524
3,90631215,2010 Jan 05 12:00:00 AM,2010 Jan 05 12:00:00 AM,150,6,Hollywood,646,2,900,VIOLATION OF COURT ORDER,...,IC,Invest Cont,900.0,998.0,NaN,NaN,CAHUENGA BL,HOLLYWOOD BL,34.1016,-118.3295
4,100100501,2010 Jan 03 12:00:00 AM,2010 Jan 02 12:00:00 AM,2100,1,Central,176,1,122,"RAPE, ATTEMPTED",...,IC,Invest Cont,122.0,NaN,NaN,NaN,8TH ST,SAN PEDRO ST,34.0387,-118.2488